spring.application.name=tollbackend-test

spring.data.mongodb.uri=mongodb+srv://tolladmin:Toll%40123@tolldb.gtda4qq.mongodb.net/tolldb?retryWrites=true&w=majority&appName=tolldb

server.port=${PORT:8080}